Feature/crud admin conab
conab-devs/conab-frontend-web pull request #16
Opened 2020-09-11 14:38 UTC by hdev14

## Descrição :pencil:
Foram desenvolvidas todas as telas de CRUD para os administradores da CONAB. Além disso foram adicionadas a ferramentas de padronização de código (editorconfig, eslint) e aglumas refatorações no código.

**Issues :pushpin:**
#2 

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [x] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [x] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:

![image](https://user-images.githubusercontent.com/44510574/92937491-c71ebd00-f421-11ea-97aa-30529e833480.png)
![image](https://user-images.githubusercontent.com/44510574/92937564-dbfb5080-f421-11ea-93dd-dff6ac4aa267.png)
![image](https://user-images.githubusercontent.com/44510574/92937598-e7e71280-f421-11ea-84cb-2b2f78c6d59a.png)
![image](https://user-images.githubusercontent.com/44510574/92937637-f6352e80-f421-11ea-8c88-73feb62ef228.png)
![image](https://user-images.githubusercontent.com/44510574/92938598-1d403000-f423-11ea-9a1c-b91b7d64f1f0.png)

2020-09-14 12:04 UTC, lucasemanuel8 approved these changes

2020-09-18 14:38 UTC, FrankKleiton reviewed
Lendo superficialmente não me parece ter mais nenhum problema! Mas meu dia hoje está corrido, então não fiz o pull, vou deixar pra ler bem no fim de semana! O comentário adicional que tenho é que nós 3 vamos ter que gastar um bom tempo componentizando, Fernando tinha razão, não li pra debugar e entender bem porque é uma review no github, mas ficou bem extenso o código e além da feature de Lucas, haverá o Gerenciar Admin Cooperativa que usará os mesmos componentes, eu também fiz uns buttons que vocês fizeram, então na integração a gente vai ter que optar o código que vai jogar fora e componentizar isso pra reusar, já que os botôes e esses formulários estão sendo usados mais de 1 vez.

2020-09-18 14:38 UTC, FrankKleiton commented on src/pages/AdminProfile/index.js
> +              ? `${process.env.REACT_API_URL}/storage/${admin.profile_picture}`
Aquele problema de você não conseguir a url completa já não havia sido resolvido não?

2020-09-18 15:13 UTC, FrankKleiton requested changes

2020-09-18 15:13 UTC, FrankKleiton commented on src/pages/AdminProfile/index.js
> +              ? `${process.env.REACT_API_URL}/storage/${admin.profile_picture}`
Aquele problema de você não conseguir a url completa já não havia sido resolvido não?

2020-09-19 14:39 UTC, hdev14 commented on src/pages/AdminProfile/index.js
> +              ? `${process.env.REACT_API_URL}/storage/${admin.profile_picture}`
Já! como eu tinha dito eu preciso gera a url no endpoint do update, então eu deixa dessa forma por enquanto para depois em outro PR refatorar. Mas acho que isso não é uma coisa importante agr.

2020-09-19 17:23 UTC, FrankKleiton approved these changes

2020-09-19 17:32 UTC, merged