Telas para gerenciar Administradores das Cooperativas
conab-devs/conab-frontend-web pull request #23
Opened 2020-10-02 18:25 UTC by lucasemanuel

## Descrição :pencil:
Adicionando telas do CRUD dos administradores da cooperativas, consumindo api do backend.

**Issues :pushpin:**
#4 

## Informações adicionais
- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [x] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:

2020-10-02 19:51 UTC, hdev14 commented
@lucasemanuel  coloca umas screenshots pra eu ver como ficou.

2020-10-02 20:32 UTC, hdev14 requested changes
As outras coisas parecem tudo correto pra min. Uma dica que posso te dá é que tem muita coisa que poderia ser transformada em outros components. O poder do react vem exatamente disso, então, depois dá uma olhada e tenta ver quais partes você poderia transformar em components no futuro.

2020-10-02 20:32 UTC, hdev14 commented on src/pages/UpdateAdminCoop/index.js
> +              SEG. TELEFONE*:
O segundo e o terceiro telefone não são obrigatórios.

2020-10-02 20:32 UTC, hdev14 commented on src/pages/AdminCoopDetail/index.js
> +                state: { cooperative },
O usuário administrador da cooperativa tem a coluna cooperative_id já.

2020-10-04 13:53 UTC, lucasemanuel commented on src/pages/AdminCoopDetail/index.js
> +                state: { cooperative },
Só que para recuperar o usuário preciso do id da cooperativa, dê uma olhada nas rotas da api.

2020-10-04 14:13 UTC, lucasemanuel commented on src/pages/UpdateAdminCoop/index.js
> +              SEG. TELEFONE*:
Vou tentar desabilitar os inputs.

2020-10-04 14:17 UTC, hdev14 commented on src/pages/UpdateAdminCoop/index.js
> +              SEG. TELEFONE*:
É só tira esse asterisco. Já meio que um conversão que quando tem um astericos o campo é obrigatório.

2020-10-04 14:24 UTC, hdev14 commented on src/pages/AdminCoopDetail/index.js
> +                state: { cooperative },
Certo, coloquei esse comentário porque seria mais fácil pega direto da retorno do administrador o id da cooperativa do que passa dois níveis abaixo na hierarquia de componentes.

2020-10-04 19:50 UTC, hdev14 reviewed
Vou esperar @FrankKleiton dá uma olhada antes pra ver a opinião dele.

2020-10-05 14:21 UTC, FrankKleiton commented on src/pages/AdminCoopDetail/index.js
> +                state: { cooperative },
Ele fez assim porque no backend busquei os usuários a partir da cooperativa inserida "encadeando" a busca, como o id é autoincrement, não tendo dois usuários com o mesmo id, daria certo também buscar o usuário diretamente no backend e simplificaria no frontend, mas assim está certo também. Cumprindo o requisito é a conta kk

2020-10-05 14:23 UTC, FrankKleiton approved these changes
Por mim está show, se @hdev14, que tem mais experiência com frontend, não tiver mais nenhuma requisição de mudança, pode merjar aí.

2020-10-05 14:24 UTC, hdev14 approved these changes
@FrankKleiton  show approved! ☕

2020-10-05 14:24 UTC, merged