Feature/manage categories
conab-devs/conab-frontend-web pull request #26
Opened 2020-10-13 22:08 UTC by FrankKleiton

## Descrição :pencil:
> Foi desenvolvido o gerenciamento de categorias de produtos. O Storybook foi usado para documentação de componentes.

**Issues :pushpin:**
> #5 

## Informações adicionais

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [ ] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:

![Screenshot_2020-10-13 Screenshot_2020-10-13_18-22-23 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921261-599adf00-0d87-11eb-837e-c37863e14293.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_18-22-51 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921276-5ef82980-0d87-11eb-81e8-e1cf36494202.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_18-23-15 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921290-67506480-0d87-11eb-85c9-74fb247e442d.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_19-00-02 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921303-6c151880-0d87-11eb-8ab4-18c24be19901.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_19-00-25 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921311-6f100900-0d87-11eb-9ccd-aa79bf5d94ad.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_19-00-48 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921318-733c2680-0d87-11eb-867a-7ac8c760a37b.png)

![Screenshot_2020-10-13 Screenshot_2020-10-13_19-01-15 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/95921325-76cfad80-0d87-11eb-95c3-a1cd711140be.png)

2020-10-17 20:15 UTC, hdev14 requested changes

2020-10-17 20:15 UTC, hdev14 commented on src/components/Category/ExcludePopup/index.js
> +const Popup = ({ exclude, message, isOpen, setIsOpen }) => {
Você poderia ter aproveitado o component modal.

2020-10-17 20:15 UTC, hdev14 commented on src/components/Category/SUPopup/index.js
> +const Popup = ({ register, buttonName, isOpen, setIsOpen, errors, setErrors }) => {
Mesma situação aqui, vc poderia ter passado form para o componente modal.

2020-10-17 21:12 UTC, lucasemanuel approved these changes

2020-10-19 16:28 UTC, hdev14 approved these changes
☕

2020-10-19 16:28 UTC, merged