Feature/refactoring reset password
conab-devs/conab-frontend-web pull request #28
Opened 2020-11-23 19:09 UTC by FrankKleiton

## Descrição :pencil:
> Foi refatorada a tela da recuperação de senha para usar um código.

**Issues :pushpin:**
fixes #27 

![Screenshot_2020-11-23 Screenshot_2020-11-23_15-58-11 png (PNG Image, 1366 × 768 pixels) — Scaled (83%)](https://user-images.githubusercontent.com/31077851/100004351-25fb9d80-2da6-11eb-8549-1479fc4f1086.png)

2020-11-23 19:42 UTC, hdev14 requested changes
Coloque as mensagem/labels em PT-BR.

2020-11-24 17:13 UTC, lucasemanuel approved these changes

2020-11-24 20:56 UTC, hdev14 commented on src/pages/ResetPassword/index.js
>      </Container>
@FrankKleiton foi o eslint que adicionou essa ruma de {" "} ?

2020-11-25 13:55 UTC, FrankKleiton commented on src/pages/ResetPassword/index.js
>      </Container>
Foi, eslint --fix

2020-11-25 16:25 UTC, hdev14 commented on src/pages/ResetPassword/index.js
>      </Container>
Deve ser algum bug kkk

2020-11-25 16:26 UTC, hdev14 approved these changes
☕

2020-11-25 16:40 UTC, merged